import { UserData } from './user';
import { Address } from './product';
import { DeliveryType } from './order';

type ProductPivot = {
    package_id: number;
    product_id: number;
    created_at: string;
    updated_at: string;
    id: number;
    quantity: number;
};

type StorePivot = {
    product_id: number;
    store_id: number;
    quantity: number;
    id: number;
    created_at: string;
    updated_at: string;
};

type Store = {
    id: number;
    name: string;
    type: string;
    pivot: StorePivot;
    address: Address;
    driver_id: number;
    driver: {
        id: number;
        user_name: string | null;
        first_name: string;
        last_name: string;
        email: string | null;
        phone_number: string;
        is_active: number;
        is_corporate_manager: boolean;
        created_at: string;
        updated_at: string;
        deleted_at: string | null;
        profile_image_path: string | null;
        profile_thumbnail_path: string | null;
    };
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
};

type Product = {
    id: number;
    cnet_id: string;
    name: string;
    name_am: string;
    slug: string | null;
    description: string | null;
    description_am: string | null;
    supplier_id: number;
    brand: string;
    size: string | null;
    measurement_type: string;
    weight: string | null;
    price: string;
    discount: string;
    max_quantity_per_order: number | null;
    category_id: number | null;
    pivot: ProductPivot;
    subcategory_id: number;
    stores: Store[];
    total_quantity: number;
    left_in_stock: number;
    rating: number | null;
    is_non_stocked: number;
    is_active: number;
    image_paths: string[];
    thumbnail_image_paths: string[];
    created_at: string;
    updated_at: string;
};

type Package = {
    id: number;
    name: string;
    name_am: string;
    is_active: number;
    price: string;
    discount: string;
    max_quantity_per_order: number | null;
    stores: Store[];
    total_quantity: number;
    left_in_stock: number;
    image_path: string;
    image_paths: string[];
    thumbnail_image_paths: string[];
    tag_id: number;
    pivot: {
        order_id: number;
        package_id: number;
        id: number;
        quantity: number;
        store_id: number | null;
    };
    products: Product[];
    created_at: string;
    updated_at: string;
};

type Invoice = {
    id: string;
    order_id: number;
    type: string;
    description: string;
    payment_method: string;
    bank_transaction_id: string | null;
    bunna_bank_transaction_id: string | null;
    bunna_bank_reference_id: string | null;
    bunna_bank_transaction_date: string | null;
    telebirr_to_pay_url: string | null;
    telebirr_transaction_no: string | null;
    apollo_transaction_no: string | null;
    telebirr_super_prepay_id: string | null;
    telebirr_super_merch_order_id: string | null;
    telebirr_super_sign: string | null;
    telebirr_super_pre_order_response: string | null;
    telebirr_super_notification: string | null;
    telebirr_super_pay_request: string | null;
    telebirr_super_pay_order_request: string | null;
    cbe_transaction_no: string | null;
    hibret_transaction_no: string | null;
    cbe_birr_response: string | null;
    cbe_birr_result_response: string | null;
    cbe_birr_conversation_id: string | null;
    cbe_birr_transaction_id: string | null;
    cbe_pay_response: string | null;
    cbe_pay_refund_response: string | null;
    cbe_pay_status_check_response: string | null;
    cbe_pay_checkout_id: string | null;
    cbe_pay_payment_id: string | null;
    boa_request_parameters: string | null;
    boa_notification: string | null;
    boa_result_message: string | null;
    boa_request_response: string | null;
    hello_cash_response: string | null;
    hello_cash_invoice_id: string | null;
    hello_cash_last_webhook_response: string | null;
    awash_wallet_transaction_id: string | null;
    awash_wallet_initiation_response: string | null;
    awash_wallet_result_response: string | null;
    enat_bank_conversation_id: string | null;
    enat_bank_acknowledgement_id: string | null;
    enat_bank_notification: string | null;
    eth_switch_order_id: string | null;
    hello_cash_paying_phone_number: string | null;
    created_at: string;
    updated_at: string;
    paid_at: string | null;
    deleted_at: string | null;
    payment_amount: number;
};

type ShippingDetail = {
    id: number;
    order_id: number;
    first_name: string | null;
    middle_name: string | null;
    last_name: string | null;
    city: string | null;
    sub_city: string | null;
    woreda: string | null;
    neighborhood: string | null;
    phone_number: string;
    house_number: string | null;
    created_at: string;
    updated_at: string;
    deleted_at: string | null;
    longitude: string | null;
    latitude: string | null;
};

export type APIOrderResponse = {
    id: number;
    status: string;
    user_id: number;
    user: UserData;
    total_cost: number;
    order_cost: number;
    discounted_cost: number;
    delivery_cost: number;
    delivery_type_id: number;
    discount_type_id: number | null;
    discount_type_name: string | null;
    discount_percentage: number | null;
    days_left_for_delivery: number;
    delivery_type: DeliveryType;
    store_id: number | null;
    additional_order_payment: string | null;
    estimated_delivery_cost: string | null;
    estimated_delivery_time: string | null;
    actual_delivery_cost: string | null;
    actual_delivery_time: string | null;
    acceptor_id: number | null;
    approver_id: number | null;
    trip_search_id: number | null;
    otp: string | null;
    payment_method: string;
    additional_payment_method: string | null;
    products: Product[];
    packages: Package[];
    invoice: Invoice;
    orderInvoices: Invoice[];
    deliveryInvoice: Invoice | null;
    shipping_detail: ShippingDetail;
    created_at: string;
    accepted_at: string | null;
    approved_at: string | null;
    delivered_at: string | null;
    deleted_at: string | null;
};
